spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.77.35.124:3306/spring-security?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: hj
    password: huangjie
  session:
    store-type: none

#security:
#  basic:
#    enabled: false

server:
  port: 80

