spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-security?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  session:
    store-type: none

#security:
#  basic:
#    enabled: false

server:
  port: 80

dream:
  security:
    browser:
     loginPage: /dream-signIn1.html
    code:
      image:
        length: 6
        width: 100
        url: /users,/user/*

